services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    network_mode: "host"  # Set network mode to host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jq3did3SmX0WntMyWCH0u5eFL
      POSTGRES_DB: pichealth

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
