services:
  convertx: 
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    ports:
      - "3035:3000"
    volumes:
      - /Hyperion/containers/convertx:/app/data