services:
  filebrowser:
    image: hurlenko/filebrowser
    ports:
      - 5092:8080
    volumes:
      - /Rhea/Ernie/ROMs:/data:ro
      - /Hyperion/containers/fileRom/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always