services:
  filebrowser:
    image: hurlenko/filebrowser
    ports:
      - 5091:8080
    volumes:
      - /Hyperion/containers/file/data:/data
      - /Hyperion/containers/file/config:/config
      - /Hyperion/containers/file/database/filebrowser.db:/database/filebrowser.db
    environment:
      - FB_BASEURL=/filebrowser
    restart: always