services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.pog-smp.xyz"
    volumes:
      - /Hyperion/containers/vaultwarden/vw-data/:/data/
    ports:
      - 4080:80