services:
  wings:
    image: ghcr.io/pelican-dev/wings:latest
    restart: always
    networks:
      - wings0
    ports:
      - "${WINGS_PORT1}:${WINGS_PORT1}"
      - "${WINGS_PORT2}:${WINGS_PORT2}"
    tty: true
    environment:
      TZ: America/Los_Angeles
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pelican
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "${VOLUME_PATH}/containers/wings/config:/etc/pelican/"
      - "${VOLUME_PATH}/containers/wings/passwd:${VOLUME_PATH}/containers/wings/passwd"
      - "${VOLUME_PATH}/containers/wings/lib:${VOLUME_PATH}/containers/wings/lib"
      - "${VOLUME_PATH}/containers/wings/log:${VOLUME_PATH}/containers/wings/pelican/"
      - "${VOLUME_PATH}/containers/wings/tmp:${VOLUME_PATH}/containers/wings/tmp"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      - "${VOLUME_PATH}/containers/wings/certs:/certs"
      # you may need /srv/daemon-data if you are upgrading from an old daemon
      #- "/srv/daemon-data/:/srv/daemon-data/"
      # Required for SSL if you use Let's Encrypt. Uncomment to use.
      #- "/etc/letsencrypt/:/etc/letsencrypt/"
    env_file:
      - .env
      
networks:
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.34.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0
