services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - "/Hyperion/containers/jdownloader-2:/config:rw"
      - "/Hyperion/Downloads/jDown:/output:rw"
    restart: unless-stopped